export const NAV_ITEMS = {
  patient: [
    { id: "dashboard", label: "Dashboard", icon: "🏠" },
    { id: "medicines", label: "Medicines", icon: "💊" },
    { id: "appointments", label: "Appointments", icon: "📅" },
    { id: "health", label: "Health Tracker", icon: "❤️" },
    { id: "reports", label: "Reports", icon: "📄" },
    { id: "chat", label: "Doctor Chat", icon: "💬" },
    { id: "profile", label: "My Profile", icon: "👤" },
    { id: "ai", label: "AI Assistant", icon: "🤖" },
  ],
  doctor: [
    { id: "dashboard", label: "Dashboard", icon: "🏠" },
    { id: "patients", label: "My Patients", icon: "🧑‍⚕️" },
    { id: "appointments", label: "Appointments", icon: "📅" },
    { id: "prescriptions", label: "Prescriptions", icon: "📝" },
    { id: "analytics", label: "Analytics", icon: "📊" },
    { id: "chat", label: "Messages", icon: "💬" },
    { id: "profile", label: "Profile", icon: "👤" },
  ],
  nurse: [
    { id: "dashboard", label: "Dashboard", icon: "🏠" },
    { id: "vitals", label: "Vitals Monitor", icon: "📡" },
    { id: "tasks", label: "Tasks", icon: "✅" },
    { id: "logs", label: "Med Logs", icon: "📋" },
    { id: "alerts", label: "Alerts", icon: "🚨" },
    { id: "schedule", label: "Schedule", icon: "🗓️" },
    { id: "profile", label: "Profile", icon: "👤" },
  ],
  admin: [
    { id: "dashboard", label: "Dashboard", icon: "🏠" },
    { id: "users", label: "Users", icon: "👥" },
    { id: "doctors", label: "Doctors", icon: "🩺" },
    { id: "revenue", label: "Revenue", icon: "💰" },
    { id: "analytics", label: "Analytics", icon: "📊" },
    { id: "notifications", label: "Notifications", icon: "🔔" },
    { id: "logs", label: "System Logs", icon: "🗂️" },
    { id: "settings", label: "Settings", icon: "⚙️" },
  ],
};
